version: '3' 
services: 
  wordpress: 
    image: wordpress 
    environment: 
      ## esta linea busca el contenedor y su puerto
      WORDPRESS_DB_HOST: dbserver:3306
      WORDPRESS_DB_USER: wordpress 
      WORDPRESS_DB_PASSWORD: mysqlpw 
      WORDPRESS_DB_NAME: wordpress 
    ports: 
      - 9012:80 
    ##esto quiere decir que hasta que no esta arrancada la base de datos, no se arramque el wordpress
    depends_on: 
      - dbserver 
  dbserver: 
    image: mysql:5.7 
    environment: 
      MYSQL_ROOT_PASSWORD: mysqlpw 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: mysqlpw 
    ports: 
      - 3100:3306